[package]
name = "oauth_server"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
serde = "1.0.125"
serde_json = "1.0.64" 
quick-error = "2.0.0"
dotenv = "0.15.0"
tap = "1.0.1"
tokio = { version = "1.5.0", features = ["full"] }
sqlx = { version = "0.5.2", features = [ "runtime-tokio-rustls", "uuid", "json", "postgres", "offline", "macros", "migrate"] }