# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "test56_rest"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"
# links = "opencv_core" # TODO: ??? Линкуем с библиотеками, поиск в build.rs (links, 2, 3, 4, links...)

# TODO: только нужные значения опций
# TODO: rustls

[dependencies]
log = "0.4.13"
pretty_env_logger = "0.4.0"
actix-web = "3.3.2"
actix-multipart = "0.3.0"
serde = "1.0.120"
serde_json = "1.0.61"
http = "0.2.3"
futures = "0.3.12"
libc = "0.2.82"
dirs = "3.0.1"
scopeguard = "1.1.0"
base64 = "0.13.0"
tokio-util = "0.3.1"
tokio = {version = "0.2.24", features = ["fs"]}
uuid = {version = "0.8.2", features = ["v4"]}

[dev-dependencies]
actix-rt = "1.1.1"
reqwest = {version = "0.10.10", features = ["json", "stream"]} # "multipart"
url = "2.2.0"
# actix-multipart-rfc7578 = "0.2.1"
# multipart = "0.17.1"

[build-dependencies]
bindgen = "0.56.0"
# cc = "1.0.66"