# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "test41_tokio"
version = "0.1.0"
authors = ["Pavel Ershov <pershov@game-insight.com>"]
edition = "2018"

[dependencies]
tokio = { version="0.2.15", features = ["full"] } # features = ["full", "macros", "rt-threaded", "sync", "stream", "time"]
futures = "0.3.4"
bytes = { version = "0.5.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
byteorder = "1.3.4"
rand = "0.7.3"
uuid = { version = "0.8.1", features = ["v4"] }
# futures-core = "0.3.4"
# futures-util = "0.3.4"

[build-dependencies]
tonic-build = "0.2.0"