version: "3.8"
services:
  app:
    image: devnul/test58_oauth
    container_name: test58_oauth
    restart: always
    env_file:
        - credentials/test_environment_docker.env
    volumes:
        - ./credentials:/oauth_server/credentials
        - ./logs:/oauth_server/logs
        - ./db/oauth_db.sqlite:/oauth_server/db/oauth_db.sqlite
    ports:
      - 8080:8080