# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "test49_python_lib"
version = "0.1.0"
authors = ["Pavel Ershov <pershov@game-insight.com>"]
edition = "2018"

[lib]
name = "rust_python_lib"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = {version = "0.11.1", features = ["extension-module"]}