[package]
name = "uploader_app"
version = "0.1.0"
authors = ["Pavel Ershov <pershov@game-insight.com>"]
edition = "2018"

[features]
default = []
flame_it = ["flame", "flamer"]

[dependencies]
tokio = {version="0.2.24", features=["full"]} # TODO: Убрать часть фичей https://docs.rs/crate/tokio/0.3.6/features
tokio-util = {version="0.3.1", features=["codec"]}
reqwest = {version="0.10.9", default-features=false, features=["stream", "rustls-tls"]}
lazy_static = "1.4.0"
futures = "0.3.8"
serde_json = "1.0.60"
log = "0.4.11"
env_logger = "0.8.2"
clap = "2.33.3"
async-trait = "0.1.42"
dirs = "3.0.1"
qrcode = "0.12.0"
image = "0.23.12"
yup-oauth2 = "4.1.3"
google-drive = {path="../../cio/drive", features=["rustls"]}
slack_client_lib = {path="../../slack_client_lib", features=["rustls", "sql"]}
app_center_client = {path="../../app_center_client", features=["rustls"]}
any_field_is_some = {path="libs/any_field_is_some"}
flame = {version="0.2.2", optional=true}
flamer = {version="0.4.0", optional=true}
# slack_client_lib = {features=["rustls"], git="https://github.com/DevNulPavel/slack_client_lib.git", rev="a76bfb33a2719a511c305b275d191bc5571bd65f"}
# app_center_client = {features=["rustls"], git="https://github.com/DevNulPavel/app_center_client.git", rev="b73b30b7f82f33ad0f1949ee1bfe05ac1af00bc7"}

[dev-dependencies]
rand = "0.8.0"