[package]
name = "test32_vst_plugin"
version = "0.1.0"
authors = ["DevNul <devnulpavel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.2.0"
rand = "0.7.3"
rustfft = "3.0.1"
# sample = "0.10.0"
apodize = "1.0.0"

[lib]
name = "test32_vst_plugin"
crate-type = ["cdylib", "rlib"]