[package]
name = "test19_cbindgen"
version = "0.1.0"
authors = ["DevNul <devnulpavel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "test19_cbindgen"
crate-type = ["staticlib"] # Создаем статическую библиотеку, для python - cdylib, варианты: dylib, rlib, staticlib, cdylib, proc-macro

# [target.armv7-linux-androideabi]

# [target.aarch64-linux-android]

# [profile.dev]
# opt-level = 0
# debug = true # Дебажная информация
# rpath = false
# lto = false # Оптимизация линковки, чтобы бинарь был поменьше
# debug-assertions = true
# codegen-units = 16 # Степень параллельной сборки
# panic = "unwind"   # Что  делсть в случае паники, "abort"
# incremental = true # Инкрементальная сборка
# overflow-checks = true

# [profile.release]
# opt-level = 3
# debug = false
# rpath = false
# lto = false
# debug-assertions = false
# codegen-units = 16
# panic = "unwind"
# incremental = false
# overflow-checks = false

# [profile.test]
# opt-level = 0
# debug = 2
# rpath = false
# lto = false
# debug-assertions = true
# codegen-units = 16
# incremental = true
# overflow-checks = true

# [profile.bench]
# opt-level = 3
# debug = false
# rpath = false
# lto = false
# debug-assertions = false
# codegen-units = 16
# incremental = false
# overflow-checks = false

[dependencies]
# libc = "0.2.66"
maplit = "1.0.2"
lazy_static = "1.4.0"